name: deploy

on: # 조건 정의
  push: # main 브랜치 push할 경우 발생
    branches:
      - main

jobs: # 할 작업들을 정의
  build: # 작업 이름
    runs-on: ubuntu-latest

    steps:
      # 현재 저장소의 코드를 클론
      - name: Checkout
        uses: actions/checkout@v4

      # Java JDK 21을 설치
      - name: Install Java JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Gradle 빌드
      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew clean build

      # Docker 로그인
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest

      # 6. EC2 배포
      - name: Deploy to EC2 with Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ci_cd_practice
            docker-compose down
            docker-compose pull
            docker-compose up -d

